// <auto-generated />
using FigurasGeometricasApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FigurasGeometricasApi.Migrations
{
    [DbContext(typeof(FigurasContext))]
    [Migration("20251028184606_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("FigurasGeometricasApi.Models.Figura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Figuras");

                    b.HasDiscriminator<string>("Tipo").HasValue("Figura");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FigurasGeometricasApi.Models.Circulo", b =>
                {
                    b.HasBaseType("FigurasGeometricasApi.Models.Figura");

                    b.Property<double>("Radio")
                        .HasColumnType("REAL");

                    b.HasDiscriminator().HasValue("Circulo");
                });

            modelBuilder.Entity("FigurasGeometricasApi.Models.Rectangulo", b =>
                {
                    b.HasBaseType("FigurasGeometricasApi.Models.Figura");

                    b.Property<double>("Altura")
                        .HasColumnType("REAL");

                    b.Property<double>("Base")
                        .HasColumnType("REAL");

                    b.HasDiscriminator().HasValue("Rectangulo");
                });

            modelBuilder.Entity("FigurasGeometricasApi.Models.Triangulo", b =>
                {
                    b.HasBaseType("FigurasGeometricasApi.Models.Figura");

                    b.Property<double>("LadoA")
                        .HasColumnType("REAL");

                    b.Property<double>("LadoB")
                        .HasColumnType("REAL");

                    b.Property<double>("LadoC")
                        .HasColumnType("REAL");

                    b.HasDiscriminator().HasValue("Triangulo");
                });
#pragma warning restore 612, 618
        }
    }
}
